import { ChannelConfig } from './types';

export const DEFAULT_CHANNELS: ChannelConfig[] = [
  { id: 'meta', name: 'Meta', allocation: 0.45, ctr: 0.013, installRate: 0.20, cpm: 12.0 },
  { id: 'tiktok', name: 'TikTok', allocation: 0.20, ctr: 0.010, installRate: 0.18, cpm: 9.0 },
  { id: 'google', name: 'Google', allocation: 0.25, ctr: 0.050, installRate: 0.35, cpm: 15.0 },
  { id: 'linkedin', name: 'LinkedIn', allocation: 0.10, ctr: 0.006, installRate: 0.12, cpm: 25.0 },
];

export const EXPLANATIONS = {
  targetOnboard: "The total number of new users you want to successfully onboard by the end of the time period.",
  timeframeMonths: "The duration of the media plan in months. The target onboard goal is distributed evenly across these months.",
  installsPerOnboard: "How many app installs (downloads) it typically takes to produce 1 onboarded user. Example: '10' means 10 installs → 1 onboarded user.",
  cpi: "Cost per Install. How much you pay on average for a single app install. If derived mode is on, CPI is computed from CPM, CTR and install_rate.",
  ctr: "Click-Through Rate: clicks ÷ impressions. Example: 0.013 = 1.3% CTR.",
  cpm: "Cost per 1000 impressions. Used in 'Derive CPI' mode to estimate CPC and therefore CPI.",
  installRate: "Install conversion rate from click (installs ÷ clicks). Example: 0.20 = 20% of clicks lead to installs.",
  onboardedPerInstall: "Onboard ratio explained: installs ÷ installs_per_onboard = onboarded users.",
  overallCPI: "Weighted CPI across channels (when in Derive CPI mode) computed using channel allocations as weights.",
  derivedCPI: "CPI derived as CPC ÷ install_rate. Example: if CPC=0.50 and install_rate=0.2, CPI=2.50",
  // Table Header Tooltips
  totalSpend: "Total marketing budget spent across all channels for this month.",
  totalInstalls: "Total new app installs generated by all channels combined.",
  totalOnboard: "Total users who successfully completed onboarding.",
  cumOnboard: "Cumulative total of onboarded users up to this month.",
  // Per Channel Tooltips
  chSpend: "Budget allocated to this specific channel.",
  chCPI: "Cost Per Install for this channel (Fixed or Derived).",
  chInstalls: "Volume of installs driven by this channel.",
  chOnboard: "Users onboarded attributed to this channel.",
  // Pacing & Efficiency
  pacingMode: "Choose how your target is distributed: 'Linear' (even split) or 'Growth' (ramps up over time).",
  monthlyGrowthRate: "For Growth pacing: The percentage increase in onboard targets month-over-month.",
  efficiencyRate: "Efficiency Gain: Percentage reduction in CPI each month (simulating optimization or organic lift).",
};

export const COLORS = {
  Meta: '#3b82f6', // blue-500
  TikTok: '#000000', // black
  Google: '#ef4444', // red-500
  LinkedIn: '#0a66c2', // linkedin blue
  Generic: '#8b5cf6', // violet-500
};